version: '3'
services:
  redis-benchmark:
    image: redis:7.2.3
    command: tail -F anything
    container_name: redis-benchmark
    networks:
      - app-tier
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    ports:
      - 5379:6379
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M  
  rcache:
    image: lsk569937453/rcache:test
    container_name: rcache
    networks:
      - app-tier
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M 
networks:
  app-tier:
    driver: bridge
